apiVersion: nuclio.io/v1beta1
kind: Function
metadata:
  name: lpis-es-castillayleon-pipe-archive-processor
  namespace: fast-platform
  labels:
    platform: fast
    module: core
    data: lpis
    ms: es
    region: castillayleon
spec:
  alias: latest
  description: Ingest a shapefile archive and send each reacord as a GeoJSON feature in a Kafka topic
  handler: main:handler
  image: eufast/lpis-es-castillayleon-pipe-archive-processor:0.1.0
  replicas: 1
  maxReplicas: 1
  runtime: python:3.6
  env:
  - name: KAFKA_BOOTSTRAP_SERVER
    value: "kafka-broker.kafka:9092"
  - name: TARGET_TOPIC
    value: lpis-es-castillayleon-pipe
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 2
      memory: 4Gi 
  triggers:
    kafka:
      kind: kafka
      attributes:
        topic: "lpis-es-castillayleon-pipe-download"
        partitions: [0,1,2]
      url: "kafka-broker.kafka:9092"
  version: -1
status:
  state: waitingForResourceConfiguration
